language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - rbx-18mode
 - rbx-19mode
 - ruby-head
env:
 - "rake=0.8"
script: "bundle exec rspec"
matrix:
  allow-failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
notifications:
  email: false
